language: node_js
cache: yarn
node_js: '10'
install: yarn install --pure-lockfile
script: yarn build
notifications:
  email: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_17e0da069064_key -iv $encrypted_17e0da069064_iv
  -in deploy.key.enc -out deploy.key -d
- chmod 600 deploy.key
- eval `ssh-agent -s`
- ssh-add deploy.key
deploy:
- provider: script
  skip_cleanup: true
  script: yarn release-it -n --preRelease=nightly
- provider: npm
  skip_cleanup: true
  email: ekoeryanto@gmail.com
  api_key:
    secure: P6qte7duUJAeepD2VWD+0knH27ymAXD6VjMZf3Cpa8iaMKQETp33+xdwnO1SCuI9eUDcClm392E9U8Cc0yKmpd2TbmWJMo1Z8A+rY4PBxlQ/Dka2yG4lSET5zjgJqXwJTSZroumkzv9xvQ7D89V4givpPXZK3d9nAlXvNw1332wyUfFatYx1/c4ZN0VR4eDNjm8t+uDoOf6dL5GoKV0NIS+GcdZ+W9MLiUrbJ2Da/C7ow94tjDspzkMIclI462aGlXTGRHqWV30gL/sOiLQi5STjh4OFa/CtVJVxch+NnaM31UKpU6OHTarJpAhCEsziGajyzYkahC2LbXMlabxsB4NTpGgZKv0aXK7rHiSE8vzcIlQNeW5/vXPdKRlWZkATEq8ZDF3hMBa5yZvLExhrJT5cE0/OwUgdVXltFt+iriSj9Zpt1yKe0jLF0NyVOJlutigQzxy438wKQlBduEaQb78wRMhh5BIzVntpnSbM2gRbiJdoMD63LBVxbKWND5v8P6LjU54Sn+meOe3pkb3mPsboWvoTdAp44bZFcOwenN4A9qUoypy4v9goCFR2LFl9o4ujEuoVkSFU9s4+itriOrrOhj94KOuFpaIBIu/YU6mhxciFyDNkWLBHxcRmfOmlgd26abcrPOfnVoUoSzskm555qIogqkc2T0lqPF8D6Pk=
  tag: nightly
env:
  global:
    secure: LBe9TRbFWGSmx5N97vsVCokIF3ck06NXw5Sag0DigLVaC+TYiughpaot0BNcER+922I7A0lcRm3SGr94YnF+ZC/k1ut4BTCFyPK4lBgGjz6ACLsO/Pi2r619yw0l8NYZg6GWcWpTU0gW2CX57nremlEzq7n2w/S5UHmktRO+2ECLvmijrxiYToPsSS3CzoEKg02lu0ibqxmyGM84aIJSI+setOe4Mk9hxGdQ2lhnAB74TVk6//CDaL7WHUyyIbgEAMEcWTxvAgNPcNwGDdMMPa4JkWwa/FILpXacu4jkwrHXGJzpO7Z/7255VYYuCTk1GRbo4B8MD5cWCrpH58Gl60pk7LeGtv75fMajCUH/uekspdPK2ZUK0TiNG05IcigVzbFpS3VCZCvgWwO04EAiYhQCfq3tGTnNYWTuwdxsQm2WAy03415tHk8C8/BSiGSrUy+ndpRm/J3i7tFSZHmh5EdRSM74zoOMzcvtCnu1u+qYsWdlH8qAnkEeW3euC95wdeb7aGb4CBG5zJ2+eHt1DeRgCm0L1HRSxb9nY4Z6/fcoF8Sq4GS7fzPE5erb/jiQUvqKQaB/3i8xnrv2dxXRhWj6JwwITgTw7FIiSL7HFLl+YM3+DERTMHG/hWREHiwM4O/ztVmsGJgOMqlZEReCqn3Z6amsh9gCOE+6/O/PHvQ=
